#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2015
# Kamil Lulko, <rev13@wp.pl>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= stm32-primer.o
#obj-y	+= led.o
